### PR TITLE
feat: Ephemeral messages

### PR DESCRIPTION
**Pull request by ItsSyfe**
Added functions to use ephemeral messages, next steps to use this freely is to improve the settings menu (to allow each command to have its own settings) and then pass a flag through each command to indicate if we should send only ephemeral messages for the command.

### CODE REVIEW

**Comment by VillainsRule** [comment]
Very well aware, discussing this with Xotic and deciding how to implement this properly.
The reality is, there is nothing preventing users from sticking to an older version of the tool and using DeafBot freely. 🤷

**Comment by VillainsRule** [comment]
What part of the ToS states this?

**Comment by zastlx** [comment]
> We have some strict guidelines on what Mods are allowed, you are only allowed to create mods that do not have an impact on the experience of other Users, by a negative impact on the experience of other Users we mean any Mod that automates a task that would provide an advantage against another User such as automating bazaar transactions, or unofficial **“chat bots” and/or “self bots”** which negatively impact the experience of other User's experiences within our chat. We have the final say on what constitutes a negative impact on other Users experiences and what doesn't within a Mod.
It's important to us that 3rd party tools/services don't seem “official” as we can't guarantee their quality. We also reserve the right to takedown Mods or other software that violates our TOS or EULA.

**Comment by VillainsRule** [comment]
I didn't see the EULA. I need to finish a few bugs on the typescript version of BetterBlacket, and then I'll publish a modified version. The bazaar sniper will be force disabled for all users (similar code to the Message Logger), and DeafBot will be forced to ephemeral commands.

It shocks me that Blacket has gotten smaller and smaller in both freedom of speech and scripting. When I joined Blacket Legacy, there were almost no rules in place of scripting nor speech, including ridiculously offensive messages and advanced "multi-tools" some owners at the time built to make hundreds of accounts and trade to tokens. Mentioning one of these "multi-tools" today would likely result in a blacklist, as well as saying several of the things owners had said in the past. Blacket was a game that allowed me to develop my coding knowledge as well as have fun on, but this era seems to be coming to a close. These new regulations on chatting placed on one-message bots are part of the reason users quit every day as they no longer find Blacket a remotely fun place. As you cut down on these tools and utilities people enjoy, including the users who cannot use them, you cut down on the fun experience of Blacket. There is a reason users often are found deserting the Blacket chat, and it is hard to find people with many badges there before. These changes to Blacket's ToS & the creation of the EULA are very interesting, as it's unclear exactly why these changes were made. DeafBot & it's friends, like Confidence, never actually caused major chatting issues, and it seemed like users could simply work around them. I have, being the major builder of these tools, spent time to make sure this worked. I took Confidence offline for a week while Xotic built and developed rooms to cut down chat spam, which caused many users to be angry, despite the good intentions behind it. The utter lack of involvement in Blacket v2 that you seem to have is highlighted by the plethora of bugs I report to you every day, to be ignored because Blacket v3 is simply more important. However, you seem to conjure the time to write a long EULA banning chat tools that never caused large harm to the game. As I know the actions in the past, these rules likely will not be repealed. However, I wish with the community that Blacket would be an actually fun game again.

**Pull request closed without merging**
