### PR TITLE
fix speedup + fix images not loading

### PR DESCRIPTION
**Pull request by zastlx**
blacket has migrated to using webps for images and speedup still referenced pngs causing it to not load the image, and a check in one of the patches was also broken

### CODE REVIEW

**Comment by VillainsRule** [comment]
ez remove speedup ok sexy lemme do this in a few mins

**Comment by VillainsRule** [comment]
fixed in 6dd26f6c8678a18c9adf4bd282a5caecdb202f84

**Comment by zastlx** [comment]
> fixed in [6dd26f6](https://github.com/VillainsRule/BetterBlacket/commit/6dd26f6c8678a18c9adf4bd282a5caecdb202f84)

"fixed", you just deleted speedup, what happened to rewriting bb in typescript? how about you delete an actual banned plugin like bazaar sniper! how about you actually abide by the TOS! your so immature.

**Comment by zastlx** [comment]
also deleting my blacket alt url because your mad is hilarious

**Comment by zastlx** [comment]
and you didnt even remove monxys url, the one that doesnt actually work, :coffee:

**Comment by VillainsRule** [comment]
so I'm gonna try to send this because I don't have full access to GitHub
right now

you evidently saw my discord message, and removing me from the bppv2 repo
is a terrible way to rage. you failed to address any of the points that I
brought up, yet you decide to call me immature. do I need to post
screenshots only a week old of things you say? my members surfaced those
quickly. attacking me in these ways is stupid and gets you nothing.

this argument was literally started by you getting angry and abusing your
powers because I surfaced screenshots that you would rather keep nice and
hidden. i moderated in turn, and so you blacklisted me for "lol" (or
something else, I can't care to check) and then banned me from blacket.
thanks to methods, I saw you later told okr this occured because I was
'posting nsfw'. sadly, you finding evidence to back this up will be a
challenge. and sadly, I don't care anymore. you've chosen to blacklist me
and defame me, so what do I lose for breaking ToS? maybe I'll make it into
the announcements for being a terrible traitor like doxy or any of the
other OGs you couldn't tolerate and exiled so rudely. or maybe you'll try
to cover up my ban like you did with many others. shame that you hated
someone so much you doxxed them, called them a pedophile, attempted to ruin
their game, and then came crawling back to kick to lick his boots. shame
that you are so quick to abuse your power to save your own ass rather than
protect those around you. shame that your go-to when someone gets mad at
you is to blacklist them. i could go on, but it's pointless, since although
you'll never admit it and attempt to now defame me further, deep down you
know I'm right.

now that you've finished reading this big chunk, let's see how you're going
to try to ruin me next. remove my collaborator on more repos? so sad lulz!

**Comment by ThatFruedDued** [comment]
🍿🍿🍿

**Comment by VillainsRule** [comment]
lulz okr

**Pull request closed without merging**
